### ISSUE TITLE
Summer of Bitcoin project ideas

### ISSUE THREAD

**Issue by kouloumos** [mit-dci/libutreexo#13]
Utreexo [is part of Summer of Bitcoin](https://www.summerofbitcoin.org/project-ideas-details?recordId=recd8CF7zeCAAtFIf) but with no C++ project ideas.

After a brief discussion with @kcalvinalvin, I am opening this issue in order to get @dergoegge take on what work needs to be done and if from that a project idea could be potentially created. 

Calvin already mentioned that some tests need to be ported to the C++ implementation, so apart from a more solid project idea, it would be great to get a few guidelines on things I can tackle while preparing for my proposal.

**Comment by dergoegge** [comment]
Hi Andreas, thank you for your interest!

I have not thought much about concrete projects, so i will just list some things that still need work.

1. As you mentioned, working on adding tests would be helpful. 
2. I recently added some simple fuzzing tests which could also be built out further.
3. Adding benchmark tests. This would be helpful to make sure that we don't degrade performance when changing things and would also give us an incentive to improve performance. 
4. Most of the complexity in this library comes from the caching mechanism that helps with reducing the proof sizes. If you have a look at https://github.com/mit-dci/libutreexo/blob/32ef51b2a63e7f74f6054ef1e63d193ca06d6634/src/pollard.cpp#L343 or https://github.com/mit-dci/libutreexo/blob/32ef51b2a63e7f74f6054ef1e63d193ca06d6634/src/pollard.cpp#L480 you can see what i mean, those two functions are not the easiest to understand. Creating an implementation of the accumulator that can't do caching could be nice to have a minimal implementation that is not super complex. This would also be a cool project for you because you get to rewrite some of the algorithms from scratch. (if you like that kind of stuff)

An example for 1. would be to a test for the `RamForest` that specifically tests `RamForest::Undo`. The `simple_blockchain` test already tests `RamForest::Undo` but i think having a dedicated test would also be good.https://github.com/mit-dci/libutreexo/blob/32ef51b2a63e7f74f6054ef1e63d193ca06d6634/src/test/accumulator_tests.cpp#L433-L441

I think 3. and/or 4. might be candidates for a SoB project. I will try to think of more projects/things to work on and add them to this issue.

I don't know how much you have looked at Utreexo, so if you have any questions about the above let me know. I remember when i first got started with this project a lot of the algos were not the easiest to understand. We have an IRC channel #utreexo on libera, feel free to join and ask questions there as well.

**Comment by kouloumos** [comment]
I took some time to deep dive into the codebase to get more familiar and further validate that this interests me. I believe that I now have a pretty good understanding of how everything works. Still, as this is transliteration of the go reference implementation, I think that inevitably I'll have to look that one also.

Regarding adding unit tests, I've run test coverage for the unit tests and it seems that only some unhappy paths are untested. What you mentioned about a specific test for `RamForest::Undo` seems redundant as apart from `simple_blockchain` this is also tested in the `simple` test. I am not sure how a dedicated test adds any more value, however I wrote one and with that I tried to cover another untested path. You can see those changes at #14.

Benchmarking is interesting and if I can do a similar approach to what Bitcoin Core is doing, I could potentially also use that experience there. The minimal implementation is also cool and something that could be used as a baseline for benchmarking the caching mechanism of the accumulator, so I think that those 2 could be combined for a SoB project. I've also noticed a few TODOs in the implementation that I could also work on. 

This is an intriguing project and working on it as part of SoB is something that stills interests me. 
In the [guide section of SoB](https://guide.summerofbitcoin.org/the-proposal-round/about) it says

> You are free to propose your own project idea too, as long as that project idea is from one of the participating organizations.

That said, as Utreexo is a participating organization, I am not sure if for me to be able to propose a project idea for this implementation, you must create [a new project idea](https://www.summerofbitcoin.org/project-ideas-details?recordId=recd8CF7zeCAAtFIf) or I can just write a proposal without it. I'll ask in the discord server, but as the proposal process requires the participants to show interested for a specific idea and then assign a proposal to that idea through the dashboard, I think that you might need create a new project idea.

**Comment by kcalvinalvin** [comment]
Hey thanks for the PR. I'll take a look.

Regarding Summer of Bitcoin: Utreexo is a participating organization as Tadge and I are mentors. For Summer of Bitcoin specific stuff, do contact either one of us (I'm easier to get hold of).

I'm not aware of exact summer of bitcoin rules but if you need me to make a project, happy to do so.

**Comment by kouloumos** [comment]
Thanks for the quick reply.

I asked in the discord server and it seems that the process is simpler if a project idea exists, so if you can create one it would be great!

**Comment by kouloumos** [comment]
https://www.summerofbitcoin.org/project-ideas-details?recordId=recd8CF7zeCAAtFIf
